version: "2.3"
services:

  docker-mysql:
    image: mysql:latest
    build:
      context: .
      dockerfile: mysql_dockerfile
    ports:
    - 3306:3306
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=test
    - MYSQL_PASSWORD=root
    - MYSQL_USER=root
  springbootapp:
    ports:
      - 8091:8091
    build:
      context: .
      dockerfile: DockerFile
    image: demo
    depends_on:
    - docker-mysql
    environment:
    - DATABASE_HOST=docker-mysql
    - DATABASE_USER=root
    - DATABASE_PASSWORD=root
    - DATABASE_NAME=test
    - DATABASE_PORT=3306

