version: "2.3"
services:

  docker-mysql:
    image: mysql:latest
    container_name: test-mysql
    ports:
    - 3306:3306
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=test
    - MYSQL_PASSWORD=root

  springbootapp:
    ports:
      - 8080:8080
    image: dockerlab
    depends_on:
    - docker-mysql
    environment:
    - DATABASE_HOST=docker-mysql
    - DATABASE_USER=root
    - DATABASE_PASSWORD=root
    - DATABASE_NAME=test
    - DATABASE_PORT=3306

